//	VCP Codes

onevcpcode(00, "Code Page"                                      , RW      , T   , Mandatory   , 2.2   )
onevcpcode(04, "Restore Factory Defaults"                       , WO      , NC  ,             ,       )
onevcpcode(05, "Restore Factory Luminance / Contrast Defaults"  , WO      , NC  ,             ,       )
onevcpcode(06, "Restore Factory Geometry Defaults"              , WO      , NC  ,             ,       )
onevcpcode(08, "Restore Factory Color Defaults"                 , WO      , NC  ,             ,       )
onevcpcode(0A, "Restore Factory TV Defaults"                    , WO      , NC  ,             ,       )
onevcpcode(B0, "Settings"                                       , WO      , NC  ,             ,       )
onevcpcode(0B, "User Color Temperature Increment"               , RO      , NC  ,             , 2.2   )
onevcpcode(0C, "User Color Temperature"                         , RW      , C   ,             , 2.2   )
onevcpcode(0E, "Clock"                                          , RW      , C   ,             ,       )
onevcpcode(10, "Luminance"                                      , RW      , C   ,             ,       )
onevcpcode(11, "Flesh Tone Enhancement"                         , RW      , NC  ,             ,       )
onevcpcode(12, "Contrast"                                       , RW      , C   ,             ,       )
onevcpcode(13, "Backlight Control"                              , RW      , C   ,             , < 2.2 )
onevcpcode(14, "Select Color Preset"                            , RW      , NC  ,             ,       )
onevcpcode(16, "Video Gain (Drive): Red"                        , RW      , C   ,             ,       )
onevcpcode(17, "User Color Vision Compensation"                 , RW      , C   ,             ,       )
onevcpcode(18, "Video Gain (Drive): Green"                      , RW      , C   ,             ,       )
onevcpcode(1A, "Video Gain (Drive): Blue"                       , RW      , C   ,             ,       )
onevcpcode(1C, "Focus"                                          , RW      , C   ,             ,       )
onevcpcode(1E, "Auto Setup"                                     , RW      , NC  ,             ,       )
onevcpcode(1F, "Auto Color Setup"                               , RW      , NC  ,             ,       )
onevcpcode(2E, "Gray Scale Expansion"                           , RW      , NC  ,             ,       )
onevcpcode(3E, "Clock Phase"                                    , RW      , C   ,             ,       )
onevcpcode(56, "Horizontal Moiré"                               , RW      , C   ,             ,       )
onevcpcode(58, "Vertical Moiré"                                 , RW      , C   ,             ,       )
onevcpcode(59, "6 Axis Saturation Control: Red"                 , RW      , C   ,             ,       )
onevcpcode(5A, "6 Axis Saturation Control: Yellow"              , RW      , C   ,             ,       )
onevcpcode(5B, "6 Axis Saturation Control: Green"               , RW      , C   ,             ,       )
onevcpcode(5C, "6 Axis Saturation Control: Cyan"                , RW      , C   ,             ,       )
onevcpcode(5D, "6 Axis Saturation Control: Blue"                , RW      , C   ,             ,       )
onevcpcode(5E, "6 Axis Saturation Control: Magenta"             , RW      , C   ,             ,       )
onevcpcode(6B, "Backlight Level: White"                         , RW      , C   ,             ,       )
onevcpcode(6C, "Video Black Level: Red"                         , RW      , C   ,             ,       )
onevcpcode(6D, "Backlight Level: Red"                           , RW      , C   ,             ,       )
onevcpcode(6E, "Video Black Level: Green"                       , RW      , C   ,             ,       )
onevcpcode(6F, "Backlight Level: Green"                         , RW      , C   ,             ,       )
onevcpcode(70, "Video Black Level: Blue"                        , RW      , C   ,             ,       )
onevcpcode(71, "Backlight Level: Blue"                          , RW      , C   ,             ,       )
onevcpcode(72, "Gamma"                                          , RW      , NC  ,             ,       )
onevcpcode(73, "LUT Size"                                       , RO      , T   ,             ,       )
onevcpcode(74, "Single Point LUT Operation"                     , RW      , T   ,             ,       )
onevcpcode(75, "Block LUT Operation"                            , RW      , T   ,             ,       )
onevcpcode(7C, "Adjust Zoom"                                    , RW      , C   ,             ,       )
onevcpcode(87, "Sharpness"                                      , RW      , C   ,             ,       )
onevcpcode(88, "Velocity Scan Modulation"                       , RW      , C   ,             ,       )
onevcpcode(8A, "Color Saturation"                               , RW      , C   ,             ,       )
onevcpcode(8C, "TV-Sharpness"                                   , RW      , C   ,             ,       )
onevcpcode(8E, "TV-Contrast"                                    , RW      , C   ,             ,       )
onevcpcode(90, "Hue"                                            , RW      , C   ,             ,       )
onevcpcode(92, "TV-Black Level / Luminance"                     , RW      , C   ,             ,       )
onevcpcode(9A, "Window Background"                              , RW      , C   ,             ,       )
onevcpcode(9B, "6 Axis Hue Control: Red"                        , RW      , C   ,             ,       )
onevcpcode(9C, "6 Axis Hue Control: Yellow"                     , RW      , C   ,             ,       )
onevcpcode(9D, "6 Axis Hue Control: Green"                      , RW      , C   ,             ,       )
onevcpcode(9E, "6 Axis Hue Control: Cyan"                       , RW      , C   ,             ,       )
onevcpcode(9F, "6 Axis Hue Control: Blue"                       , RW      , C   ,             ,       )
onevcpcode(A0, "6 Axis Hue Control: Magenta"                    , RW      , C   ,             ,       )
onevcpcode(A2, "Auto Setup On / Off"                            , WO      , NC  ,             ,       )
onevcpcode(A4, "Window Mask Control"                            , RW      , T   ,             ,       )
onevcpcode(A5, "Window Select"                                  , RW      , C   ,             ,       )
onevcpcode(A6, "Window Size"                                    , RW      , C   ,             ,       )
onevcpcode(A7, "Window Transparency"                            , RW      , C   ,             ,       )
onevcpcode(AA, "Screen Orientation"                             , RO      , NC  ,             ,       )
onevcpcode(D4, "Stereo Video Mode"                              , RW      , NC  ,             ,       )
onevcpcode(DC, "Display Application"                            , RW      , NC  ,             ,       )
onevcpcode(B4, "Source Timing Mode"                             , RW      , T   ,             ,       )
onevcpcode(CA, "OSD / Button Control"                           , RW      , NC  ,             ,       )
onevcpcode(AC, "Horizontal Frequency"                           , RO      , C   ,             ,       )
onevcpcode(AE, "Vertical Frequency"                             , RO      , C   ,             ,       )
onevcpcode(B5, "Source Color Coding"                            , WO      , NC  ,             ,       )
onevcpcode(C0, "Display Usage Time"                             , RO      , C   ,             ,       )
onevcpcode(C8, "Display Controller ID"                          , RO      , NC  , Mandatory   ,       )
onevcpcode(C9, "Display Firmware Level"                         , RO      , C   ,             ,       )
onevcpcode(CC, "OSD Language"                                   , RW      , NC  ,             ,       )
onevcpcode(D6, "Power Mode"                                     , RW      , NC  ,             ,       )
onevcpcode(DB, "Image Mode"                                     , RW      , NC  ,             ,       )
onevcpcode(DF, "VCP Version"                                    , RO      , NC  , Mandatory   ,       )
onevcpcode(20, "Horizontal Position (Phase)"                    , RW      , C   ,             ,       )
onevcpcode(22, "Horizontal Size"                                , RW      , C   ,             ,       )
onevcpcode(24, "Horizontal Pincushion"                          , RW      , C   ,             ,       )
onevcpcode(26, "Horizontal Pincushion Balance"                  , RW      , C   ,             ,       )
onevcpcode(28, "Horizontal Convergence R/B"                     , RW      , C   ,             ,       )
onevcpcode(29, "Horizontal Convergence M/G"                     , RW      , C   ,             ,       )
onevcpcode(2A, "Horizontal Linearity"                           , RW      , C   ,             ,       )
onevcpcode(2C, "Horizontal Linearity Balance"                   , RW      , C   ,             ,       )
onevcpcode(30, "Vertical Position {Phase}"                      , RW      , C   ,             ,       )
onevcpcode(32, "Vertical Size"                                  , RW      , C   ,             ,       )
onevcpcode(34, "Vertical Pincushion"                            , RW      , C   ,             ,       )
onevcpcode(36, "Vertical Pincushion Balance"                    , RW      , C   ,             ,       )
onevcpcode(38, "Vertical Convergence R/B"                       , RW      , C   ,             ,       )
onevcpcode(39, "Vertical Convergence M/G"                       , RW      , C   ,             ,       )
onevcpcode(3A, "Vertical Linearity"                             , RW      , C   ,             ,       )
onevcpcode(3C, "Vertical Linearity Balance"                     , RW      , C   ,             ,       )
onevcpcode(40, "Horizontal Parallelogram"                       , RW      , C   ,             ,       )
onevcpcode(41, "Vertical Parallelogram"                         , RW      , C   ,             ,       )
onevcpcode(42, "Horizontal Keystone"                            , RW      , C   ,             ,       )
onevcpcode(43, "Vertical Keystone"                              , RW      , C   ,             ,       )
onevcpcode(44, "Rotation"                                       , RW      , C   ,             ,       )
onevcpcode(46, "Top Corner Flare"                               , RW      , C   ,             ,       )
onevcpcode(48, "Top Corner Hook"                                , RW      , C   ,             ,       )
onevcpcode(4A, "Bottom Corner Flare"                            , RW      , C   ,             ,       )
onevcpcode(4C, "Bottom Corner Hook"                             , RW      , C   ,             ,       )
onevcpcode(82, "Horizontal Mirror (Flip)"                       , RW      , NC  ,             ,       )
onevcpcode(84, "Vertical Mirror (Flip)"                         , RW      , NC  ,             ,       )
onevcpcode(86, "Display Scaling"                                , RW      , NC  ,             ,       )
onevcpcode(95, "Window Position (TL_X)"                         , RW      , NC  ,             ,       )
onevcpcode(96, "Window Position (TL_Y)"                         , RW      , C   ,             ,       )
onevcpcode(97, "Window Position (BR_X)"                         , RW      , C   ,             ,       )
onevcpcode(98, "Window Position (BR_Y)"                         , RW      , C   ,             ,       )
onevcpcode(DA, "Scan Mode"                                      , RW      , NC  ,             ,       )
onevcpcode(01, "Degauss"                                        , WO      , NC  ,             ,       )
onevcpcode(02, "New Control Value"                              , RW      , NC  , Mandatory   ,       )
onevcpcode(03, "Soft Controls"                                  , RO      , NC  ,             ,       )
onevcpcode(52, "Active Control"                                 , RO      , NC  , Mandatory   ,       )
onevcpcode(54, "Performance Preservation"                       , RW      , NC  ,             ,       )
onevcpcode(60, "Input Select"                                   , RW      , NC  ,             ,       )
onevcpcode(66, "Ambient Light Sensor"                           , RW      , NC  ,             ,       )
onevcpcode(76, "Remote Procedure Call"                          , WO      , T   ,             ,       )
onevcpcode(78, "Display Identification Data Operation"          , RO      , T   ,             ,       )
onevcpcode(8B, "TV-Channel Up / Down"                           , WO      , NC  ,             ,       )
onevcpcode(B2, "Flat Panel Sub-Pixel Layout"                    , RO      , NC  ,             ,       )
onevcpcode(B6, "Display Technology Type"                        , RO      , NC  ,             ,       )
onevcpcode(C2, "Display Descriptor Length"                      , RO      , C   ,             ,       )
onevcpcode(C3, "Transmit Display Descriptor"                    , RW      , T   ,             ,       )
onevcpcode(C4, "Enable Display of ‘Display Descriptor’"         , RW      , NC  ,             ,       )
onevcpcode(C6, "Application Enable Key"                         , RO      , NC  ,             ,       )
onevcpcode(C7, "Display Enable Key"                             , RO      , NC  , Deprecated  , < 2.2 )
onevcpcode(CD, "Status Indicators (Host)"                       , RW      , NC  ,             ,       )
onevcpcode(CE, "Auxiliary Display Size"                         , RO      , NC  ,             ,       )
onevcpcode(CF, "Auxiliary Display Data"                         , WO      , T   ,             ,       )
onevcpcode(D0, "Output Select"                                  , RW      , NC  ,             ,       )
onevcpcode(D2, "Asset Tag"                                      , RW      , T   ,             ,       )
onevcpcode(D7, "Auxiliary Power Output"                         , RW      , NC  ,             ,       )
onevcpcode(DE, "Scratch Pad"                                    , RW      , NC  ,             ,       )
onevcpcode(62, "Audio: Speaker Volume"                          , RW      , NC  ,             ,       )
onevcpcode(63, "Speaker Select"                                 , RW      , NC  ,             ,       )
onevcpcode(64, "Audio: Microphone Volume"                       , RW      , C   ,             ,       )
onevcpcode(65, "Audio: Jack Connection Status"                  , RO      , NC  ,             ,       )
onevcpcode(8D, "Audio Mute / Screen Blank"                      , RW      , NC  ,             ,       )
onevcpcode(8F, "Audio Treble"                                   , RW      , NC  ,             ,       )
onevcpcode(91, "Audio Bass"                                     , RW      , NC  ,             ,       )
onevcpcode(93, "Audio Balance L/R"                              , RW      , NC  ,             ,       )
onevcpcode(94, "Audio Processor Mode"                           , RW      , NC  ,             ,       )
onevcpcode(B7, "Monitor Status"                                 , RO      , NC  ,             ,       )
onevcpcode(B8, "Packet Count"                                   , RW      , C   ,             ,       )
onevcpcode(B9, "Monitor X Origin"                               , RW      , C   ,             ,       )
onevcpcode(BA, "Monitor Y Origin"                               , RW      , C   ,             ,       )
onevcpcode(BB, "Header Error Count"                             , RW      , C   ,             ,       )
onevcpcode(BC, "Body CRC Error Count"                           , RW      , C   ,             ,       )
onevcpcode(BD, "Client ID"                                      , RW      , C   ,             ,       )
onevcpcode(BE, "Link Control"                                   , RW      , NC  ,             ,       )
onevcpcode(E0, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(E1, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(E2, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(E3, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(E4, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(E5, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(E6, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(E7, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(E8, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(E9, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(EA, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(EB, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(EC, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(ED, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(EE, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(EF, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(F0, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(F1, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(F2, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(F3, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(F4, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(F5, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(F6, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(F7, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(F8, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(F9, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(FA, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(FB, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(FC, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(FD, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(FE, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )
onevcpcode(FF, "Manufacturer Specific"                          , TBD     , TBD ,             ,       )

#undef onevcpcode
